[package]
name = "poseidon2-starky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = { version = "^0.4.2", default-features = false }
anyhow = "1.0.71"
plonky2 = "0.1.3"
starky = "0.1.1"
zkhash = { git = "https://github.com/0xmozak/poseidon2", package = "zkhash" }
num = { version = "0.4", default-features = false, features = ["rand"] }
lazy_static = "1.4"

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }

[[bench]]
name = "poseidon2_starky"
harness = false
