[package]
name = "poseidon2-starky"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = "0.1.3"
starky = "0.1.1"
zkhash = { git = "https://github.com/HorizenLabs/poseidon2.git", package = "zkhash" }
num = { version = "0.4", default-features = false, features = ["rand"] }
