name: ci

on:
  merge_group: {}
  push:
    branches: [ "main" ]
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: poseidon2-starky
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: poseidon2-starky
    steps:
      - uses: actions/checkout@v3
      - name: Install clippy and rustfmt
        run: rustup component add clippy rustfmt
      - name: Run clippy linter
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Check cargo fmt
        run: cargo fmt --check
